###服务启动端口号
server:
  port: 8500
###服务名称(服务注册到eureka名称)  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
spring:
  application:
    name: app-goods
  redis:
    host: 10.9.216.1
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  ###数据库相关连接
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meite_product?useUnicode=true&characterEncoding=UTF-8
  data:
    elasticsearch:
      ####集群名称
      cluster-name: elk-es
      ####地址
      cluster-nodes: 10.9.216.1:9300
