eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/
server:
  port: 8001
spring:
  application:
    name: zuul
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meite_gateway?useUnicode=true&characterEncoding=UTF-8&useSSL=true
# 配置网关反向代理
zuul:
  routes:
    APP-MEMBER:
      path: /member/**
      serviceId: APP-MEMBER
    APP-WEIXIN:
      path: /weixin/**
      serviceId: APP-WEIXIN
    APP-PORTAL-WEB:
      path: /portal-web/**
      serviceId: APP-PORTAL-WEB
    APP-PORTAL-PAY-WEB:
      path: /portal-pay-web/**
      serviceId: APP-PORTAL-PAY-WEB
    APP-PAY:
      path: /pay/**
      serviceId: APP-PAY
    APP-AUTH:
      path: /auth/**
      serviceId: APP-AUTH
    APP-INTEGRAL:
      path: /integral/**
      serviceId: APP-INTEGRAL
    APP-GOODS:
      path: /goods/**
      serviceId: APP-GOODS
management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env
#用 serviceId 进行路由时，使用 ribbon.ReadTimeout 和 ribbon.SocketTimeout 设置
#用指定 url 进行路由时，使用 zuul.host.connect-timeout-millis 和 zuul.host.socket-timeout-millis 设置
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000