server:
  port: 8800
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
spring:
  application:
    name:  app-integral
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.7.1:3306/meite_integral?useUnicode=true&characterEncoding=UTF-8&useSSL=true
  rabbitmq:
    ####连接地址
    host: 192.168.7.1
    ####端口号
    port: 5672
    ####账号
    username: lipeng
    ####密码
    password: lipeng
    ### 地址
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        retry:
          ####开启消费者（程序出现异常的情况下会）进行重试
          enabled: true
          ####最大重试次数
          max-attempts: 5
          ####重试间隔时间
          initial-interval: 1000
        ####开启手动ack  
        acknowledge-mode: manual
        default-requeue-rejected: false