eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
server:
  port: 9800
spring:
  application:
    name: app-spike
  redis:
    host: 10.9.216.1
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  ###数据库相关连接
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meite_spike?useUnicode=true&characterEncoding=UTF-8&useSSL=true
  rabbitmq:
    ####连接地址
    host: 10.9.216.1
    ####端口号
    port: 5672
    ####账号
    username: lipeng
    ####密码
    password: lipeng
    ### 地址
    virtual-host: /
    listener:
      simple:
        retry:
          ####开启消费者（程序出现异常的情况下会）进行重试
          enabled: true
          ####最大重试次数
          max-attempts: 5
          ####重试间隔时间
          initial-interval: 1000
        ####开启手动ack
        acknowledge-mode: manual
        default-requeue-rejected: false