server:
  port: 8600
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
spring:
  application:
    name: app-pay
  redis:
    host: 10.9.216.1
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
  ###数据库相关连接
  datasource:
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/meite_pay?useUnicode=true&characterEncoding=UTF-8&useSSL=true
  rabbitmq:
    host: 10.9.216.1
    port: 5672
    username: lipeng
    password: lipeng
    virtual-host: /
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        retry:
          ####开启消费者（程序出现异常的情况下会）进行重试
          enabled: true
          ####最大重试次数
          max-attempts: 5
          ####重试间隔时间
          initial-interval: 1000
        ####开启手动ack
        acknowledge-mode: manual
        default-requeue-rejected: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
###多线程配置
threadPool:
  ###核心线程数
  corePoolSize: 10
  ###最大线程数
  maxPoolSize: 20
  ##  队列容量
  queueCapacity: 16
xxl:
  job:
    executor:
      logpath: /data/applogs/xxl-job/jobhandler
      appname: xxl-job-executor-lipeng-pay
      port: 9999
      logretentiondays: 1
      ip:
    admin:
      #admin的地址 如果admin有context-path 要加上
      addresses: http://127.0.0.1:8080
    accessToken: