#### 整合freemarker
spring:
  freemarker:
    cache: false
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
    template-loader-path:
      - classpath:/templates
  application:
    name: app-portal-web
  redis:
    host: 10.9.216.1
    port: 6379
    pool:
      max-idle: 100
      min-idle: 1
      max-active: 1000
      max-wait: -1
    timeout: 300
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
server:
  port: 80
wechat:
  appid: wx470a2431b9b88785
  secret: 67abdde46af2431d2545de16c1291336
  reDirectUri: http://127.0.0.1:80/wx/getAccessToken
qq:
  appid: 101820705
  appkey: 29f89de0c6d05d8761385a004e0e5ca9
  reDirectUri: http://9b009f9b.ngrok.io/qqLoginBack
  defaultPicUrl: http://t-1.tuzhan.com/d1bf9b24b13e/c-1/m/2012/09/21/17/0772844269934cce8980bebcc76ce396.jpg
###设置feign客户端超时时间
###SpringCloud feign 默认开启支持ribbon
ribbon:
  ###指的是建立连接后从服务器读取到可用资源所用的时间。
  ReadTimeout: 3000
  ###指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间。
  ConnectTimeout: 3000
###开启Hystrix断路器
feign:
  hystrix:
    enabled: true
#### hystrix开启
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 10000
###建议 hystrix服务超时时间大致5-10  如果产生业务延迟比较长 建议使用mq 或者异步请求

xxl-sso:
  excluded:
    paths:
xxl:
  sso:
    server: http://xxlssoserver.com:8080/xxl-sso-server
    logout:
      path: /logout
    redis:
      address: 10.9.216.1:6379